# Deal with Numpy NDArray

The foundation for numerical computation in Python is the `numpy` package, and essentially all scientific libraries in Python build on this - e.g. `scipy`, `pandas`, `statsmodels`, `scikit-learn`, `cv2` etc. The basic data structure in `numpy` is the NDArray, and it is essential to become familiar with how to slice and dice this object.

## Basic Array Manipulation

### Array Creation

In [9]:
# From (nested) list
print(np.array([1,3,4,6]))
print(np.array([[1,3,5], [7,9,11]]))

[1 3 4 6]
[[ 1  3  5]
 [ 7  9 11]]


In [13]:
# From range, arithmetic sequence, can also in log scale
print(np.arange(1,10,2))
print(np.linspace(0,1,11))
print(np.logspace(-5,3,9))

[1 3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[1.e-05 1.e-04 1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [17]:
# Basic matrices
print(np.ones((2,3)))
print(np.zeros(5))
print(np.eye(3))
print(np.diag([1,2,3]))

[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [82]:
# From function, function must be vectorized
factorial = lambda x: 1 if x <= 1 else x * factorial(x-1)
print(np.fromfunction(lambda i,j: np.vectorize(factorial)(i+j), (4,5)))

[[   1    1    2    6   24]
 [   1    2    6   24  120]
 [   2    6   24  120  720]
 [   6   24  120  720 5040]]


In [85]:
#From iterable object, especially for generator, dtype must be specified explicitly
A = [2,5,3,7,1,0,4]
print(np.fromiter((factorial(x) for x in A), dtype=int))

[   2  120    6 5040    1    1   24]


### Array Property

In [31]:
A = np.array([[1,2,3,4],[5,6,7,8]]) + 0.1
print(A.shape, A.size, A.dtype)

(2, 4) 8 float64


In [32]:
A_cplx = A + 1j * A
A_cplx

array([[1.1+1.1j, 2.1+2.1j, 3.1+3.1j, 4.1+4.1j],
       [5.1+5.1j, 6.1+6.1j, 7.1+7.1j, 8.1+8.1j]])

In [33]:
# Transpose
A_cplx.T

array([[1.1+1.1j, 5.1+5.1j],
       [2.1+2.1j, 6.1+6.1j],
       [3.1+3.1j, 7.1+7.1j],
       [4.1+4.1j, 8.1+8.1j]])

In [34]:
# Conjugate
A_cplx.conj()

array([[1.1-1.1j, 2.1-2.1j, 3.1-3.1j, 4.1-4.1j],
       [5.1-5.1j, 6.1-6.1j, 7.1-7.1j, 8.1-8.1j]])

In [35]:
# Cast to other data type
A.astype(int)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
# Reshape
A.reshape((4,2))

array([[1.1, 2.1],
       [3.1, 4.1],
       [5.1, 6.1],
       [7.1, 8.1]])

In [42]:
# As long as the rest dimension can be determined, you can just use -1
print(A.reshape((-1,2)))
print(A.reshape((4,-1)))

[[1.1 2.1]
 [3.1 4.1]
 [5.1 6.1]
 [7.1 8.1]]
[[1.1 2.1]
 [3.1 4.1]
 [5.1 6.1]
 [7.1 8.1]]


In [36]:
# Reshape to a vector
A.reshape(-1)

array([1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1])

### Array Indexing and Slicing

In [86]:
A = np.arange(1,16).reshape((3,5))
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [91]:
print('Slice 0-th row return a 1D vector')
print(A[0]) # or A[0,:]
print('Slice last column return a 1D vector')
print(A[:, -1])

print('Slice 0-th row return a 1D row vector, i.e. keep dimension')
print(A[[0]]) # or A[0,:]
print('Slice last column return a 1D column vector, i.e. keep dimension')
print(A[:, [-1]])

print('Sub-array slicing')
print(A[:2, 1:-1])

print('Extract entries by subscripts, i.e. entries with subscripts (1,3), (1,4), (2,0)')
print(A[[1,1,2], [3,4,0]])

print('Boolean indexing, i.e. entries has factor 3')
print(A[A%3==0])

Slice 0-th row return a 1D vector
[1 2 3 4 5]
Slice last column return a 1D vector
[ 5 10 15]
Slice 0-th row return a 1D row vector, i.e. keep dimension
[[1 2 3 4 5]]
Slice last column return a 1D column vector, i.e. keep dimension
[[ 5]
 [10]
 [15]]
Sub-array slicing
[[2 3 4]
 [7 8 9]]
Extract entries by subscripts, i.e. entries with subscripts (1,3), (1,4), (2,0)
[ 9 10 11]
Boolean indexing, i.e. entries has factor 3
[ 3  6  9 12 15]


### Reduction

In [95]:
print('sum of whole array')
print(A.sum())
print('column sums')
print(A.sum(axis=0))
print('row sums')
print(A.sum(axis=1))
print('row sums, keep dimension')
print(A.sum(axis=1, keepdims=True))

sum of whole array
120
column sums
[18 21 24 27 30]
row sums
[15 40 65]
row sums, keep dimension
[[15]
 [40]
 [65]]


In [99]:
# other reduction
print(A.max(axis=0))
print(A.min(axis=1))
print(np.prod(A, axis=0, keepdims=True))

[11 12 13 14 15]
[ 1  6 11]
[[ 66 168 312 504 750]]


### Broadcasting

Broadcasting refers to the set of rules that numpy uses to perfrom operations on arrays with different shapes. 
Basically when operating with two arrays, one can view this as automatic filling the dummy dimension of one array when two arrays can align the rest dimensions. 

For detailed explanation, refer to official [documentation](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html) for a clear explanation of the rules. 
Array shapes can be manipulated using the `reshape` method or by inserting a new axis with `np.newaxis`. Note that `np.newaxis` is an alias for `None`, which I sometimes use in my examples.

In [101]:
# Normalize data for the whole array
print(A.mean(), A.std())
print( (A - A.mean()) / A.std() )

8.0 4.320493798938574
[[-1.62018517 -1.38873015 -1.15727512 -0.9258201  -0.69436507]
 [-0.46291005 -0.23145502  0.          0.23145502  0.46291005]
 [ 0.69436507  0.9258201   1.15727512  1.38873015  1.62018517]]


In [104]:
# Normalize data along columns (you can do minus between 3x5 array and length-5 vector)
print((A - A.mean(axis=0)) / A.std(axis=0))

[[-1.22474487 -1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487  1.22474487]]


In [109]:
# Leave-one-out sum along rows (keepdims is necessary, since we are fill the 1-th dimension)
print( A.sum(axis=1, keepdims=True) - A )

[[14 13 12 11 10]
 [34 33 32 31 30]
 [54 53 52 51 50]]


### Example: Calculating pairwise distance matrix using broadcasting and vectorization
Calculate the pairwise distance matrix between the following points

- (0,0)
- (4,0)
- (4,3)
- (0,3)

In [115]:
def distance_matrix_py(pts):
    """Returns matrix of pairwise Euclidean distances. Pure Python version."""
    n, p = len(pts), len(pts[0])
    m = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            s = 0
            for k in range(p):
                s += (pts[i,k] - pts[j,k])**2
            m[i, j] = s**0.5
    return m

In [116]:
def distance_matrix_np(pts):
    """Returns matrix of pairwise Euclidean distances. Vectorized numpy version."""
    return np.sum((pts[None,:] - pts[:, None])**2, -1)**0.5

In [134]:
pts = np.array([(0,0), (4,0), (4,3), (0,3)])
print('Fill dummy dimension as first dimension')
print(pts[None,:], pts[None,:].shape)
print('Fill dummy dimension as last dimension')
print(pts[:,None], pts[:,None].shape)
print('Use broadcasting to compute difference, the inner most length-2 array is the difference between points in x,y axis')
print(pts[None, :] - pts[:, None])
print('Square the array, sum along the last dimension and then take square root')
print(np.sum((pts[None, :] - pts[:, None])**2, -1))

Fill dummy dimension as first dimension
[[[0 0]
  [4 0]
  [4 3]
  [0 3]]] (1, 4, 2)
Fill dummy dimension as last dimension
[[[0 0]]

 [[4 0]]

 [[4 3]]

 [[0 3]]] (4, 1, 2)
Use broadcasting to compute difference, the inner most length-2 array is the difference between points in x,y axis
[[[ 0  0]
  [ 4  0]
  [ 4  3]
  [ 0  3]]

 [[-4  0]
  [ 0  0]
  [ 0  3]
  [-4  3]]

 [[-4 -3]
  [ 0 -3]
  [ 0  0]
  [-4  0]]

 [[ 0 -3]
  [ 4 -3]
  [ 4  0]
  [ 0  0]]]
Square the array, sum along the last dimension and then take square root
[[ 0 16 25  9]
 [16  0  9 25]
 [25  9  0 16]
 [ 9 25 16  0]]


In [123]:
print(distance_matrix_py(pts))
print(distance_matrix_np(pts))

[[0. 4. 5. 3.]
 [4. 0. 3. 5.]
 [5. 3. 0. 4.]
 [3. 5. 4. 0.]]
[[0. 4. 5. 3.]
 [4. 0. 3. 5.]
 [5. 3. 0. 4.]
 [3. 5. 4. 0.]]


### Example: Calculating multiple matrix multiplication using broadcasting and vectorization

In [135]:
us = np.random.random((5, 2, 3)) # 5 2x3 matrics
vs = np.random.random((5, 3, 4)) # 5 3x4 matrices

In [142]:
print('Using for loop')
for u, v in zip(us, vs):
    print(u @ v, '\n')
    
print('Using broadcasting')
print(us @ vs)

Using for loop
[[0.93534795 0.39730992 1.0622624  0.84982193]
 [0.31139688 0.22760122 0.50960285 0.34707133]] 

[[1.18930729 0.80529542 0.9461528  0.87379071]
 [1.18174244 0.72326064 0.69140808 0.69314806]] 

[[1.54572021 0.91008777 0.58252308 0.49727011]
 [0.56200891 0.3015458  0.24841023 0.13426202]] 

[[0.42961897 0.58842677 0.80254569 0.48689598]
 [0.23214605 0.29441616 0.29991837 0.11379199]] 

[[0.3625323  0.71432901 0.55369446 0.33852141]
 [0.7235258  1.5168499  1.075911   0.80366371]] 

Using broadcasting
[[[0.93534795 0.39730992 1.0622624  0.84982193]
  [0.31139688 0.22760122 0.50960285 0.34707133]]

 [[1.18930729 0.80529542 0.9461528  0.87379071]
  [1.18174244 0.72326064 0.69140808 0.69314806]]

 [[1.54572021 0.91008777 0.58252308 0.49727011]
  [0.56200891 0.3015458  0.24841023 0.13426202]]

 [[0.42961897 0.58842677 0.80254569 0.48689598]
  [0.23214605 0.29441616 0.29991837 0.11379199]]

 [[0.3625323  0.71432901 0.55369446 0.33852141]
  [0.7235258  1.5168499  1.075911   0.803